project_id = "nhsaomowshmiuygzuhzh"

[functions.stripe-webhook]
verify_jwt = false

[functions.create-product-checkout]
verify_jwt = false

[functions.create-credits-checkout]
verify_jwt = false

[functions.enhance-prompt]
verify_jwt = false

[functions.translate]
verify_jwt = false