
INSERT INTO public.reviews (author_name, title, text, rating, variant, images, helpful_count, created_at) VALUES
('Olukoya Olowofoyeku', 'Awesome Product!', 'Everything is perfect!', 5, 'Black', ARRAY['https://m.media-amazon.com/images/I/81u2GOS46YL.jpg','https://m.media-amazon.com/images/I/815bd03BHJL.jpg'], 12, '2026-04-12'),
('Benjie B', 'Mysteries along Route 66', 'Nice shirt with a picture of my book cover. Well done and a sharp clear image.', 5, 'Team Cardinal · X-Large', ARRAY['https://m.media-amazon.com/images/I/71HBhsHR+6L.jpg'], 8, '2026-04-13'),
('Gus U.', 'Quick, no problems, and I''m happy.', 'At first I was sceptical about the design as I did not see it until received, but when it arrived everything was perfect. The print was good, the design was good, shirt quality was good. Overall, I will return for more purchases.', 5, 'Style #03', ARRAY['https://m.media-amazon.com/images/I/71ag8bTBKLL.jpg'], 15, '2026-04-10'),
('Amber Stewart', 'Great wedding gift', 'This shirt was a hit at our reception. He loved it!', 5, 'Style #97', ARRAY['https://m.media-amazon.com/images/I/71TCoxDUFFL.jpg'], 6, '2026-04-07'),
('Natalie Harbold', 'Perfection!', 'My daughter had a shirt made for her boyfriend for their anniversary, and it is perfect! The graphic is amazing quality and so is the shirt itself! We will definitely use them the next time we need custom shirts.', 5, 'Style #96', ARRAY['https://m.media-amazon.com/images/I/71GncjanWgL.jpg'], 22, '2026-04-07'),
('Nicole M. Ducksworth', 'Great Work', 'Thank You For My Shirt. I Love It.', 5, 'White · 4X-Large', ARRAY['https://m.media-amazon.com/images/I/71mMFjwarXL.jpg','https://m.media-amazon.com/images/I/71hitK7WjIL.jpg'], 4, '2026-04-07'),
('Cheyanne', 'Perfect image size', 'The shirt fit perfect and the images look great.', 5, 'Style #05', ARRAY['https://m.media-amazon.com/images/I/71Q+vALfLrL.jpg'], 9, '2026-04-08'),
('Lorena', 'I loved it!!', 'I ordered a shirt for the Bruno Mars concert and omg it''s way better than I expected. I loved it!', 5, 'Style #39', ARRAY[]::text[], 3, '2026-04-11'),
('Nick Howard', 'Loved it', 'Got one for me and one for my spouse and it came out incredibly great. No smells, good fabric, great printing quality.', 5, 'Style #93', ARRAY[]::text[], 7, '2026-04-11'),
('S. Ratcliffe', 'Came early, nice print', 'The tee came a day early, tracking not updated, but nice print!!!! Fits nicely, and is a good deal for a one-off design.', 4, 'Black', ARRAY['https://m.media-amazon.com/images/I/71gQWzVTZCL.jpg'], 5, '2026-04-12'),
('Lindsey M', 'BEST T-SHIRTS ON AMAZON.', 'I''d give 10 Stars if I could. You did an AMAZING job. Quick delivery, beautiful cotton, and high quality transfer. I''m beyond thrilled.', 5, 'Athletic Heather · Large', ARRAY[]::text[], 18, '2026-03-20'),
('Michael', 'Good print quality', 'Printing is good quality and feels good while wearing. The print held up great through washing and drying. I''ll definitely be using these guys again.', 5, 'Black · Large', ARRAY[]::text[], 11, '2025-06-19'),
('Wagner Dias Pereira', 'Excellent T-shirt', 'Excellent seller. Educated, he responds quickly, and solves the problems that arise efficiently.', 5, 'Black', ARRAY[]::text[], 2, '2026-04-10'),
('Gabriel Draghici', 'Good choice', 'I received the package one week after it was marked as delivered. The product is very good, I recommend it — great quality.', 5, '0-black · Large', ARRAY['https://m.media-amazon.com/images/I/61T0f3VGKkL.jpg'], 4, '2025-12-04'),
('Seth Taylor', 'Good value', 'Amazing print. Unfortunately, the art alignment didn''t quite match where I positioned the art.', 4, 'Yellow · Large', ARRAY[]::text[], 3, '2026-04-01'),
('Kayla Stdenny', 'Make your pictures bigger', 'The picture come out smaller then you think not as collage and stuck together like in picture of product. Runs a bit bigger then actual size.', 3, 'Style #02', ARRAY['https://m.media-amazon.com/images/I/71qpcsqOnZL.jpg'], 6, '2026-04-06'),
('Carlo and David', 'Very good quality', 'Thick and great quality. Washed it many times and the stamp still looks good.', 5, '0-black · Small', ARRAY[]::text[], 5, '2026-03-23');
