// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhsaomowshmiuygzuhzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oc2FvbW93c2htaXV5Z3p1aHpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc4Mjg0NDEsImV4cCI6MjA5MzQwNDQ0MX0.gHlVPsROD1qnhzn37j30hbS_16fYVGCMTy883sdNdLA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});